version: "3.5"

services:
  mongo:
    image: mongo:4.0.4
    container_name: mongo
    ports:
      - 27017:27017
    command: mongod

  postgres:
    container_name: postgres
    build:
      dockerfile: ./Dockerfile
      context: ./docker/postgres
    ports:
      - 5432:5432
